import java.sql.Date;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mtss
 */
public class RoomSchedulerFrame extends javax.swing.JFrame
{

    
    /**
     * Creates new form RoomSchedulerFrame
     */
    public RoomSchedulerFrame()
    {
        initComponents();
        
        
        // Load the combo boxes with data.
        rebuildFacultyComboBoxes();
        rebuildDateComboBoxes();
        rebuildRoomComboBoxes();
    }
    
    public void rebuildFacultyComboBoxes()
    {
        reserveFacultyComboBox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));   
        facultyStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));
        cancelFacultyComboBox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));
    }
    
    public void rebuildDateComboBoxes()
    {
        reserveDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));
        dateReservationComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));
        cancelDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));
        
    }
    
    public void rebuildRoomComboBoxes()
    {
        roomComboBox.setModel(new javax.swing.DefaultComboBoxModel(RoomQueries.getRoomList().toArray()));   
    }
    
    public void rebulidFacultyDisplay(){
        ArrayList<ReservationEntry> reservations = ReservationQueries.getReservationsByFaculty((facultyStatusComboBox.getSelectedItem().toString()));
        String display = "";
        String statusLabel = "";
        for(ReservationEntry reservation: reservations)
        {
            display += String.format("[Reserved for] Faculty: %s, Room: %s, Seats: %d, Date: %s %n", reservation.getFaculty(), reservation.getRoom(), reservation.getSeats(), reservation.getDate());
        }
        
        ArrayList<WaitlistEntry> waitlist = WaitlistQueries.getWaitlistByFaculty((facultyStatusComboBox.getSelectedItem().toString()));
        for(WaitlistEntry waitListEntry: waitlist){
            display += String.format("[Waitlisted for]Faculty: %s, Seats: %d, Date: %s, Timestamp: %s %n", waitListEntry.getFaculty(), waitListEntry.getSeats(), waitListEntry.getDate(), waitListEntry.getTimestamp());
        }
        facultyDisplay.setText(display);
    }

    public void rebuildCancelReservationDisplay(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        waitlistPanel = new javax.swing.JTabbedPane();
        AddFaculty = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addFacultyTextField = new javax.swing.JTextField();
        addFacultyButton = new javax.swing.JButton();
        addFacultyStatusLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AddRoom = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addRoomTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        seatsTextField = new javax.swing.JTextField();
        addRoomButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        addRoomDisplay = new javax.swing.JTextArea();
        DropRoom = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        roomComboBox = new javax.swing.JComboBox<>();
        dropRoomButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        dropRoomDisplay = new javax.swing.JTextArea();
        AddDate = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        dateSpinner = new javax.swing.JSpinner();
        addDateButton = new javax.swing.JButton();
        addDateStatusLabel = new javax.swing.JLabel();
        ReserveRoom = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        reserveFacultyComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        reserveDateComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        reserveSeatsTextField = new javax.swing.JTextField();
        reserveSubmitButton = new javax.swing.JButton();
        reservationStatusLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        Cancel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cancelDateComboBox = new javax.swing.JComboBox<>();
        cancelSubmitButton = new javax.swing.JButton();
        cancelFacultyComboBox = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        cancelReservationDisplay = new javax.swing.JTextArea();
        Status = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservationListDisplay = new javax.swing.JTextArea();
        dateReservationComboBox = new javax.swing.JComboBox();
        jScrollPanel2 = new javax.swing.JScrollPane();
        waitlistDisplay = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        facultyDisplay = new javax.swing.JTextArea();
        facultyStatusComboBox = new javax.swing.JComboBox<>();
        displayReservationStatusButton = new javax.swing.JButton();
        refreshWaitlistButton = new javax.swing.JButton();
        displayFacultyStatusButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Room Scheduler");

        jLabel2.setText("Faculty Name: ");

        addFacultyTextField.setColumns(20);
        addFacultyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacultyTextFieldActionPerformed(evt);
            }
        });

        addFacultyButton.setText("Submit");
        addFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacultyButtonActionPerformed(evt);
            }
        });

        addFacultyStatusLabel.setText("    ");

        jLabel7.setText("   ");

        javax.swing.GroupLayout AddFacultyLayout = new javax.swing.GroupLayout(AddFaculty);
        AddFaculty.setLayout(AddFacultyLayout);
        AddFacultyLayout.setHorizontalGroup(
            AddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddFacultyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(AddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddFacultyLayout.createSequentialGroup()
                            .addComponent(addFacultyStatusLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addFacultyButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddFacultyLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(addFacultyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(402, Short.MAX_VALUE))
        );
        AddFacultyLayout.setVerticalGroup(
            AddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddFacultyLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(AddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addFacultyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddFacultyLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(addFacultyStatusLabel))
                    .addGroup(AddFacultyLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(addFacultyButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(390, Short.MAX_VALUE))
        );

        waitlistPanel.addTab("Add Faculty", AddFaculty);

        jLabel3.setText("Room Name:");

        jLabel8.setText("Number of Seats:");

        seatsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsTextFieldActionPerformed(evt);
            }
        });

        addRoomButton.setText("Submit");
        addRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomButtonActionPerformed(evt);
            }
        });

        addRoomDisplay.setColumns(20);
        addRoomDisplay.setRows(5);
        jScrollPane5.setViewportView(addRoomDisplay);

        javax.swing.GroupLayout AddRoomLayout = new javax.swing.GroupLayout(AddRoom);
        AddRoom.setLayout(AddRoomLayout);
        AddRoomLayout.setHorizontalGroup(
            AddRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddRoomLayout.createSequentialGroup()
                .addGroup(AddRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddRoomLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AddRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addRoomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AddRoomLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(addRoomButton))
                    .addGroup(AddRoomLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        AddRoomLayout.setVerticalGroup(
            AddRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddRoomLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(AddRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addRoomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addRoomButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        waitlistPanel.addTab("Add Room", AddRoom);

        jLabel15.setText("Room Name:");

        roomComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dropRoomButton.setText("Submit");
        dropRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropRoomButtonActionPerformed(evt);
            }
        });

        dropRoomDisplay.setColumns(20);
        dropRoomDisplay.setRows(5);
        jScrollPane3.setViewportView(dropRoomDisplay);

        javax.swing.GroupLayout DropRoomLayout = new javax.swing.GroupLayout(DropRoom);
        DropRoom.setLayout(DropRoomLayout);
        DropRoomLayout.setHorizontalGroup(
            DropRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DropRoomLayout.createSequentialGroup()
                .addGroup(DropRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DropRoomLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(dropRoomButton))
                    .addGroup(DropRoomLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(DropRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DropRoomLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        DropRoomLayout.setVerticalGroup(
            DropRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DropRoomLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(DropRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dropRoomButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        waitlistPanel.addTab("Drop Room", DropRoom);

        jLabel9.setText("Date:");

        dateSpinner.setModel(new javax.swing.SpinnerDateModel());

        addDateButton.setText("Submit");
        addDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddDateLayout = new javax.swing.GroupLayout(AddDate);
        AddDate.setLayout(AddDateLayout);
        AddDateLayout.setHorizontalGroup(
            AddDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDateLayout.createSequentialGroup()
                .addGroup(AddDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddDateLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(addDateButton))
                    .addGroup(AddDateLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(AddDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addDateStatusLabel)
                            .addGroup(AddDateLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(397, Short.MAX_VALUE))
        );
        AddDateLayout.setVerticalGroup(
            AddDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDateLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(AddDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(40, 40, 40)
                .addComponent(addDateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDateStatusLabel)
                .addContainerGap(425, Short.MAX_VALUE))
        );

        waitlistPanel.addTab("Add Date", AddDate);

        jLabel4.setText("Faculty: ");

        reserveFacultyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveFacultyComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Date: ");

        reserveDateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveDateComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("Seats Required: ");

        reserveSeatsTextField.setColumns(3);

        reserveSubmitButton.setText("Submit");
        reserveSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReserveRoomLayout = new javax.swing.GroupLayout(ReserveRoom);
        ReserveRoom.setLayout(ReserveRoomLayout);
        ReserveRoomLayout.setHorizontalGroup(
            ReserveRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReserveRoomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReserveRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservationStatusLabel)
                    .addGroup(ReserveRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ReserveRoomLayout.createSequentialGroup()
                            .addGroup(ReserveRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(ReserveRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(reserveFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(reserveDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(reserveSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(ReserveRoomLayout.createSequentialGroup()
                            .addComponent(reserveSubmitButton)
                            .addGap(26, 26, 26))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ReserveRoomLayout.createSequentialGroup()
                .addComponent(statusLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ReserveRoomLayout.setVerticalGroup(
            ReserveRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReserveRoomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReserveRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(reserveFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ReserveRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(reserveDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ReserveRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(reserveSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(reserveSubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservationStatusLabel)
                .addContainerGap(356, Short.MAX_VALUE))
        );

        waitlistPanel.addTab("Reserve Room", ReserveRoom);

        jLabel13.setText("Faculty Name:");

        jLabel14.setText("Date:");

        cancelDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cancelSubmitButton.setText("Submit");
        cancelSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSubmitButtonActionPerformed(evt);
            }
        });

        cancelFacultyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cancelReservationDisplay.setColumns(20);
        cancelReservationDisplay.setRows(5);
        jScrollPane4.setViewportView(cancelReservationDisplay);

        javax.swing.GroupLayout CancelLayout = new javax.swing.GroupLayout(Cancel);
        Cancel.setLayout(CancelLayout);
        CancelLayout.setHorizontalGroup(
            CancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(CancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cancelSubmitButton)
                        .addGroup(CancelLayout.createSequentialGroup()
                            .addGroup(CancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel13))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(CancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cancelFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cancelDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(133, 133, 133)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        CancelLayout.setVerticalGroup(
            CancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(CancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cancelFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cancelDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelSubmitButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        waitlistPanel.addTab("Cancel Reservation", Cancel);

        reservationListDisplay.setColumns(20);
        reservationListDisplay.setRows(5);
        jScrollPane1.setViewportView(reservationListDisplay);

        dateReservationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dateReservationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateReservationComboBoxActionPerformed(evt);
            }
        });

        waitlistDisplay.setColumns(20);
        waitlistDisplay.setRows(5);
        jScrollPanel2.setViewportView(waitlistDisplay);

        jLabel10.setText("Reservation Status:");

        jLabel11.setText("Waitlist Status:");

        jLabel12.setText("Faculty Status:");

        facultyDisplay.setColumns(20);
        facultyDisplay.setRows(5);
        jScrollPane2.setViewportView(facultyDisplay);

        facultyStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        displayReservationStatusButton.setText("Display");
        displayReservationStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayReservationStatusButtonActionPerformed(evt);
            }
        });

        refreshWaitlistButton.setText("Refresh");
        refreshWaitlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshWaitlistButtonActionPerformed(evt);
            }
        });

        displayFacultyStatusButton.setText("Display");
        displayFacultyStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayFacultyStatusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StatusLayout = new javax.swing.GroupLayout(Status);
        Status.setLayout(StatusLayout);
        StatusLayout.setHorizontalGroup(
            StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(StatusLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(dateReservationComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(StatusLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(4, 4, 4))
                            .addComponent(facultyStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayReservationStatusButton))
                        .addComponent(refreshWaitlistButton, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(displayFacultyStatusButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addComponent(jScrollPanel2)
                    .addComponent(jScrollPane2))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        StatusLayout.setVerticalGroup(
            StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatusLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateReservationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayReservationStatusButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatusLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshWaitlistButton))
                    .addComponent(jScrollPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatusLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(facultyStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayFacultyStatusButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        waitlistPanel.addTab("Status", Status);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(waitlistPanel)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waitlistPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFacultyButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addFacultyButtonActionPerformed
    {//GEN-HEADEREND:event_addFacultyButtonActionPerformed
        // Add the faculty to the faculty table.
        String name = addFacultyTextField.getText();
        Faculty.addFaculty(name);
        addFacultyStatusLabel.setText(name+" has been added to the Faculty.");
        
        // rebuild the reservation faculty combo box.
        rebuildFacultyComboBoxes();
    }//GEN-LAST:event_addFacultyButtonActionPerformed

    private void reserveSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveSubmitButtonActionPerformed
        String updateUser = ReservationQueries.addReservation(reserveFacultyComboBox.getSelectedItem().toString(), Integer.parseInt(reserveSeatsTextField.getText()), Date.valueOf(reserveDateComboBox.getSelectedItem().toString()));
        reservationStatusLabel.setText(updateUser);
        
    }//GEN-LAST:event_reserveSubmitButtonActionPerformed

    private void dateReservationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateReservationComboBoxActionPerformed

    }//GEN-LAST:event_dateReservationComboBoxActionPerformed

    private void seatsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatsTextFieldActionPerformed

    private void addRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomButtonActionPerformed
        // TODO add your handling code here:
        String name = addRoomTextField.getText();
        String seat = seatsTextField.getText();
        int seats = Integer.parseInt(seat);
        RoomQueries.addRoom(name, seats);
        String titleText = "";
        titleText += ("The room " + name + " with " + seats + " seats has been added." + "\n"); 
        ArrayList<ReservationEntry> reservations = ReservationQueries.getReservationsByDate();
        for(ReservationEntry reservation: reservations){
            if(reservation.getRoom().equals(name)) {
                titleText += (reservation.getFaculty() + " has reserved this room for " + reservation.getDate() + "." + "\n");
            }
        }
        addRoomDisplay.setText(titleText);
        rebuildRoomComboBoxes();
    }//GEN-LAST:event_addRoomButtonActionPerformed

    private void addFacultyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFacultyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFacultyTextFieldActionPerformed

    private void addDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDateButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd"); 
        String spinnerValue = formater.format(dateSpinner.getValue());
        Date day = Date.valueOf(spinnerValue);
        Dates.addDate(day);
        addDateStatusLabel.setText("The date " + day + " has been added.");
        
        rebuildDateComboBoxes();
        
    }//GEN-LAST:event_addDateButtonActionPerformed

    private void cancelSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSubmitButtonActionPerformed
        // TODO add your handling code here:
        String faculty = cancelFacultyComboBox.getSelectedItem().toString();
        Date date = Date.valueOf(cancelDateComboBox.getSelectedItem().toString());
        String roomName = "";
        ArrayList<ReservationEntry> facultyRoom = ReservationQueries.getReservationsByFaculty(faculty);
        for(ReservationEntry reservation: facultyRoom){
            if(reservation.getDate().equals(date)){
                roomName = reservation.getRoom();
            }
            else{
                roomName = "";
            }
        }
        ReservationQueries.cancelReservation(faculty, date);
        String titleText = "";
        titleText += ("The reservation for " + faculty + " on " + date + " has been cancelled." + "\n");
        ArrayList<ReservationEntry> reservations = ReservationQueries.getReservationsByDate();
        for(ReservationEntry reservation: reservations){
            if(reservation.getRoom().equals(roomName)) {
                titleText += (reservation.getFaculty() + " has reserved this room " + reservation.getRoom() + "." + "\n");
            }
        }
        cancelReservationDisplay.setText(titleText);
    }//GEN-LAST:event_cancelSubmitButtonActionPerformed

    private void reserveFacultyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveFacultyComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reserveFacultyComboBoxActionPerformed

    private void reserveDateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveDateComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reserveDateComboBoxActionPerformed

    private void dropRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropRoomButtonActionPerformed
        // TODO add your handling code here:
        String room = roomComboBox.getSelectedItem().toString();
        String titleText = "";
        String facultyName = "";
        String dateName = "";
        ArrayList<ReservationEntry> reservations = ReservationQueries.getReservationsByDate();
        for(ReservationEntry reservation: reservations){
            if(reservation.getRoom().equals(room)) {
                titleText += ("Faculty " + reservation.getFaculty() + " has been moved to the waitlist for date " + reservation.getDate() + "." + "\n");
                facultyName += reservation.getFaculty();
                dateName += reservation.getDate().toString();
            }
        }
        RoomQueries.dropRoom(room);
        dropRoomDisplay.setText(titleText);
    }//GEN-LAST:event_dropRoomButtonActionPerformed

    private void displayReservationStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayReservationStatusButtonActionPerformed
        // TODO add your handling code here:
        String titleText = "";
        titleText += ("Faculty Name:" + "\t" + "Room Name:" + "\t" + "Seats:" + "\t" + "Date:" + "\n"); 
        ArrayList<ReservationEntry> reservations = ReservationQueries.getReservationsByDate(Date.valueOf(dateReservationComboBox.getSelectedItem().toString()));
        for(ReservationEntry reservation: reservations)
        {
            titleText += String.format("%s" + "\t" + "%d" + "\t" + "%s" + "\t" + "%s%n", reservation.getFaculty(), reservation.getSeats(), reservation.getRoom(), reservation.getDate());
        }
        reservationListDisplay.setText(titleText);
        
    }//GEN-LAST:event_displayReservationStatusButtonActionPerformed

    private void refreshWaitlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshWaitlistButtonActionPerformed
        // TODO add your handling code here:
        String titleText = "";
        titleText += ("Faculty Name:" + "\t" + "Seats:" + "\t" + "Date:" + "\t" + "Timestamp: \n"); 
        ArrayList<WaitlistEntry> waitlist = WaitlistQueries.getWaitlistByDate();
        for(WaitlistEntry waitListEntry: waitlist){
            titleText += String.format("%s" + "\t" + "%d" + "\t" + "%s" + "\t" + "%s%n", waitListEntry.getFaculty(), waitListEntry.getSeats(), waitListEntry.getDate(), waitListEntry.getTimestamp());
        }
        waitlistDisplay.setText(titleText);
    }//GEN-LAST:event_refreshWaitlistButtonActionPerformed

    private void displayFacultyStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayFacultyStatusButtonActionPerformed
        // TODO add your handling code here:
        String titleText = "";
        ArrayList<ReservationEntry> reservations = ReservationQueries.getReservationsByFaculty(facultyStatusComboBox.getSelectedItem().toString());
        titleText += ("[Reserved for] \n Room Name:" + "\t" + "Date:" + "\n"); 
        for(ReservationEntry reservation: reservations)
        {
            titleText += String.format("%s" + "\t" + "%s%n", reservation.getRoom(), reservation.getDate());
        }
        ArrayList<WaitlistEntry> waitlist = WaitlistQueries.getWaitlistByFaculty(facultyStatusComboBox.getSelectedItem().toString());
        titleText += ("\n[Waitlisted for] \n" + "Seats:" + "\t" + "Date:" + "\n");
        for(WaitlistEntry waitListEntry: waitlist){
            titleText += String.format("%d" + "\t" + "%s%n", waitListEntry.getSeats(), waitListEntry.getDate());
        }
        facultyDisplay.setText(titleText);
    }//GEN-LAST:event_displayFacultyStatusButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RoomSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RoomSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RoomSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RoomSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new RoomSchedulerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddDate;
    private javax.swing.JPanel AddFaculty;
    private javax.swing.JPanel AddRoom;
    private javax.swing.JPanel Cancel;
    private javax.swing.JPanel DropRoom;
    private javax.swing.JPanel ReserveRoom;
    private javax.swing.JPanel Status;
    private javax.swing.JButton addDateButton;
    private javax.swing.JLabel addDateStatusLabel;
    private javax.swing.JButton addFacultyButton;
    private javax.swing.JLabel addFacultyStatusLabel;
    private javax.swing.JTextField addFacultyTextField;
    private javax.swing.JButton addRoomButton;
    private javax.swing.JTextArea addRoomDisplay;
    private javax.swing.JTextField addRoomTextField;
    private javax.swing.JComboBox<String> cancelDateComboBox;
    private javax.swing.JComboBox<String> cancelFacultyComboBox;
    private javax.swing.JTextArea cancelReservationDisplay;
    private javax.swing.JButton cancelSubmitButton;
    private javax.swing.JComboBox dateReservationComboBox;
    private javax.swing.JSpinner dateSpinner;
    private javax.swing.JButton displayFacultyStatusButton;
    private javax.swing.JButton displayReservationStatusButton;
    private javax.swing.JButton dropRoomButton;
    private javax.swing.JTextArea dropRoomDisplay;
    private javax.swing.JTextArea facultyDisplay;
    private javax.swing.JComboBox<String> facultyStatusComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPanel2;
    private javax.swing.JButton refreshWaitlistButton;
    private javax.swing.JTextArea reservationListDisplay;
    private javax.swing.JLabel reservationStatusLabel;
    private javax.swing.JComboBox<String> reserveDateComboBox;
    private javax.swing.JComboBox<String> reserveFacultyComboBox;
    private javax.swing.JTextField reserveSeatsTextField;
    private javax.swing.JButton reserveSubmitButton;
    private javax.swing.JComboBox<String> roomComboBox;
    private javax.swing.JTextField seatsTextField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextArea waitlistDisplay;
    private javax.swing.JTabbedPane waitlistPanel;
    // End of variables declaration//GEN-END:variables


}
